### PR TITLE
Add support for numeric positional predicate

### PR DESCRIPTION
**Pull request by devgertschi**
Add support for numeric positional predicate (order predicate).

(Also standardize use of constants in one place.)

### CODE REVIEW

**Comment by devgertschi** [comment]
@dsummersl please let me know if you need more information regarding this additions. I also included tests to see if the predicate queries return what they are supposed to (or not).

**Comment by dsummersl** [comment]
@devgertschi thanks so much for this addition; sorry I haven't had time to look into it yet. I'll add it to my list for today!

**Review by dsummersl — APPROVED** [review]
Looks great, thanks!

**Comment by dsummersl** [comment]
(might take me the day to release a new version - but I'll get there...)

**Comment by devgertschi** [comment]
Hello, thanks for the merge last week. Any update about the release?
(also, I noticed that I did not increment the minor version in my PR, sry for that)

**Comment by dsummersl** [comment]
Hi there,

Sorry for the late response on this - I've publish a new version (0.13.0) with your changes. Thanks so much for the contribution!

**Pull request merged**
