### PR TITLE
Tdd namespaces

### PR DESCRIPTION
**Pull request by danosaure**
Here is the sample XML file with namespaces, and just started the TDD.

### CODE REVIEW

**Comment by dsummersl** [comment]
Are you writing the implementation or would you like me to? Either way, we should commit that to this branch and get the tests passing before we merge it in. The tests mention a `evalFirstNS` - if possible we should try to add this support into `evalFirst` rather than expanding the # of functions in the library.

Thanks so much for this start!

**Comment by dsummersl** [comment]
Looked over this a little more this morning:
- xml2js is parsing the examples in your test case are parsed out of the box (no additional params or settings need to be tweaked, apparently).

If I don't hear from you I'll take a crack at adding the implementation over the weekend.

**Comment by danosaure** [comment]
Hi, sorry i was busy. I would probably prefer you to write the implementation. I have an understanding of how to do it, but it would basically requires a clone of that xml2js JSON, and replacing the NS inline.

If you would like me to help with the tests, please create a new branch for me to PR on instead of the master.

In regard to using the same function, i agree. You can expose a function like:

```
xpath.setNamespaces({x: 'uriX', y: 'uriY'});
xpath.evalFirst(...)
```

**Comment by dsummersl** [comment]
Hi @danosaure I went ahead and rebased your PR against master (with the code coverage, thx :) ), and tested the NS support.

new PR ---> https://github.com/dsummersl/node-xml2js-xpath/pull/8

It looks like NS support is already supported. Please take a look at your test cases and let me know if I've missed something. It seems like the `NAMESPACES` variable was intended to tell xml2js which namespaces were in the source document? But when I tested your examples, xml2js pulled out of the document with no changes; if I printed the result of the xml2js parse out it looked like this:

``` js
{ 'a:Root':
   { '$':
      { 'xmlns:xsi': 'http://xmlns.com',
        'xmlns:a': 'domain.a/A',
        'xmlns:b': 'domain.b/B' },
     'a:Street': [ [Object] ] } }
```

Since it looks like xml2js already does that work I removed `NAMESPACES` from the test cases, which simplified the cases, and doesn't require any change to the functions in xpath.js

But maybe I'm misinterpretting the intention there - if so, lemme know.

**Comment by danosaure** [comment]
That namespace is quite important. The way you work with namespaces is that the XML file could have defined:

```
xmlns:a="uriA"    or xmlns:b="uriA"
```

and then you would use `a` (or `b`) in your elements, but when I later query, i want to define my own prefix (xmlns:c="uriA") so that I can define my xpath with my own prefix. Technically speaking, when you have:

<a:Story  xmlns:a="uriA" xmlns:b="uriB">
    <b:Chapter />
/a:Story

it should be translated to:

<{uriA}Story>
  <{uriB}Chapter />
</{uriA}Story>

so the only thing that is important is the URIs, not the prefix.

Is it clearer?

**Comment by dsummersl** [comment]
This is really a feature that should be implemented on top of this library not in it. If you want some ideas about how to do this, feel free to ping me and I'll see if I can get something working for you.

**Pull request closed without merging**
